# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 03:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobius', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('imageUrl', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
